// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgProto.proto

package com.moviecatalogservice.services;

public interface MovieOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moviecatalogservice.services.Movie)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
