// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgProto.proto

package com.moviecatalogservice.services;

public interface ReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moviecatalogservice.services.Reply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.moviecatalogservice.services.Movie movies = 1;</code>
   */
  java.util.List<com.moviecatalogservice.services.Movie> 
      getMoviesList();
  /**
   * <code>repeated .com.moviecatalogservice.services.Movie movies = 1;</code>
   */
  com.moviecatalogservice.services.Movie getMovies(int index);
  /**
   * <code>repeated .com.moviecatalogservice.services.Movie movies = 1;</code>
   */
  int getMoviesCount();
  /**
   * <code>repeated .com.moviecatalogservice.services.Movie movies = 1;</code>
   */
  java.util.List<? extends com.moviecatalogservice.services.MovieOrBuilder> 
      getMoviesOrBuilderList();
  /**
   * <code>repeated .com.moviecatalogservice.services.Movie movies = 1;</code>
   */
  com.moviecatalogservice.services.MovieOrBuilder getMoviesOrBuilder(
      int index);
}
