// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgProto.proto

package com.moviecatalogservice.services;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.moviecatalogservice.services.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ntop = 1;</code>
   * @return The ntop.
   */
  int getNtop();
}
