// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgProto.proto

package com.moviecatalogservice.services;

public final class MsgProto {
  private MsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moviecatalogservice_services_Movie_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moviecatalogservice_services_Movie_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moviecatalogservice_services_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moviecatalogservice_services_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moviecatalogservice_services_Reply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moviecatalogservice_services_Reply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016msgProto.proto\022 com.moviecatalogservic" +
      "e.services\"*\n\005Movie\022\014\n\004name\030\001 \001(\t\022\023\n\013des" +
      "cription\030\002 \001(\t\"\027\n\007Request\022\014\n\004ntop\030\001 \001(\005\"" +
      "@\n\005Reply\0227\n\006movies\030\001 \003(\0132\'.com.moviecata" +
      "logservice.services.Movie2p\n\tTopMovies\022c" +
      "\n\013getTrending\022).com.moviecatalogservice." +
      "services.Request\032\'.com.moviecatalogservi" +
      "ce.services.Reply\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_moviecatalogservice_services_Movie_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_moviecatalogservice_services_Movie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moviecatalogservice_services_Movie_descriptor,
        new java.lang.String[] { "Name", "Description", });
    internal_static_com_moviecatalogservice_services_Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_moviecatalogservice_services_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moviecatalogservice_services_Request_descriptor,
        new java.lang.String[] { "Ntop", });
    internal_static_com_moviecatalogservice_services_Reply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_moviecatalogservice_services_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moviecatalogservice_services_Reply_descriptor,
        new java.lang.String[] { "Movies", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
